fos_rest:
    allowed_methods_listener:   false
    view:
        formats:
            rss: false
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig

fos_oauth_server:
    db_driver:           orm       # Driver availables: orm, mongodb, or propel
    client_class:        MeetPHP\OAuthServerBundle\Entity\Client
    access_token_class:  MeetPHP\OAuthServerBundle\Entity\AccessToken
    refresh_token_class: MeetPHP\OAuthServerBundle\Entity\RefreshToken
    auth_code_class:     MeetPHP\OAuthServerBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            supported_scopes: read
            auth_code_lifetime: 30
            access_token_lifetime: 36000
            refresh_token_lifetime: 1209600

nelmio_api_doc:
    sandbox:
        authentication: # default null, if set, the value of the api key is read from the query string and appended to every sandbox api call
            name: access_token
            delivery: query # query or http_basic are supported
            custom_endpoint: true # default false, if true, your user will be able to specify its own endpoint
        enabled:  true # default: true, you can set this parameter to `false` to disable the sandbox
        endpoint: http://meetphp13.loc/ # default: /app_dev.php, use this parameter to define which URL to call through the sandbox
        accept_type: application/json # default null, if set, the value is automatically populated as the Accept header
        body_format: form # default form, determines whether to send x-www-form-urlencoded data or json-encoded data in sandbox requests
        request_format:
            method: format_param # default format_param, alternately accept_header, decides how to request the response format
            default_format: json # default json, alternately xml, determines which content format to request back by default

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB


bazinga_hateoas:
    metadata:
        cache:                file
        file_cache:
            dir:              %kernel.cache_dir%/hateoas